// Generated by CoffeeScript 1.10.0
var baseDir, files, findDrive, fs, omx, play, prompt;

omx = require('omxdirector');

prompt = require('single-prompt');

fs = require('fs');

baseDir = "../";

omx.enableNativeLoop();

files = [];

findDrive = function() {
  console.log("Finding Media...");
  return fs.readdir(baseDir, function(err, files) {
    var f, i, len;
    if (err) {
      throw err;
    }
    for (i = 0, len = files.length; i < len; i++) {
      f = files[i];
      fs.stat(baseDir + f, function(err, stats) {
        if (err) {
          throw err;
        }
        if (stats.isDirectory()) {
          return console.log(f);
        }
      });
    }
    return play();
  });
};

play = function() {
  return console.log("playing...");
};

findDrive();

//# sourceMappingURL=simplePlayer.js.map
